version: "3.8"

services:
  student-app:
    build: .
    container_name: student-app
    ports:
      - "5000:5000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    depends_on:
      - otel-collector
    networks:
      - otel-network

  # OpenTelemetry Collector
  otel-collector:
    image: otel/opentelemetry-collector
    container_name: otel-collector
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    command: ["--config=/etc/otel-config.yaml"]
    networks:
      - otel-network

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
      - prometheus_data:/prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=200h
      - --web.enable-lifecycle
      - --enable-feature=otlp-write-receiver
      - --web.route-prefix=/
      # - --enable-feature=exemplar-storage
    restart: unless-stopped
    depends_on:
      - otel-collector
    networks:
      - otel-network

  # Grafana
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - otel-network
  # Tempo
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - tempo_data:/var/tempo
      - /var/tempo/traces:/var/tempo/traces
    ports:
      - "3100:3100"  # Query API (Grafana)
      - "4319:4318"  # OTLP ingestion
    depends_on:
      - otel-collector
    networks:
      - otel-network
  
  # loki
  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - loki_data:/loki
    ports:
      - "3101:3100"
    depends_on:
      - otel-collector
    networks:
      - otel-network

volumes:
  prometheus_data:
  tempo_data:
  loki_data:
networks:
  otel-network:
    driver: bridge
