receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"  

exporters:
  prometheus:
    endpoint: "0.0.0.o:9464" 
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://otel-collector:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, otlp]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]
      # exporters: [debug, otlp]

    logs:
      receivers: [otlp]
      exporters: [debug, otlp]