receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"  

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion:
      enabled: true
      
  otlphttp:
    endpoint: "http://tempo:4318"

  otlphttp/loki:
    endpoint: "http://promtail:4318" 
  
  # debug:
  #   verbosity: detailed
  # otlp:
  #   endpoint: "http://otel-collector:4317"
  #   tls:
  #     insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]