receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    # loki
  resource/add:
    attributes:
      - key: service.name
        action: upsert
        value: "unknown-service"

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"


  # otlphttp:
  #   endpoint: "http://tempo:4317"
  #   tls:
  #     insecure: true
  
  debug:
    verbosity: detailed
  otlp:
    endpoint: "http://otel-collector:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]

    metrics:
      receivers: [otlp]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [resource/add]
      exporters: [loki, debug]