receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    timeout: 5s
    # loki
  resource/add:
    attributes:
      - key: service.name
        action: upsert
        value: "student"

exporters:
  prometheus:
    endpoint: "0.0.0.0:9090"
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"


  otlp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true
  

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, resource/add]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      processors: [resource/add]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [resource/add]
      exporters: [loki]