# server:
#   http_listen_port: 9080
#   grpc_listen_port: 4318  # Enable OTLP HTTP ingestion

# positions:
#   filename: /tmp/positions.yaml

# clients:
#   - url: http://loki:3100/loki/api/v1/push

# scrape_configs:
#   - job_name: "otel-collector"
#     otlp:
#       protocols:
#         http:
#           endpoint: "0.0.0.0:4318"